import { describe, it, expect, beforeAll } from 'vitest';
import { prisma, resetDb, registerUser, createComplexForOwner, configureCourts, dateFromToday } from './helpers';

/** Owner complex with 2 courts, 60' turns 18:00–22:00 (4 turns per court per day). */
async function setup() {
  const { agent: owner, user: ownerUser } = await registerUser('DUEÑO');
  const complex = await createComplexForOwner(owner);
  await configureCourts(owner, complex, { openTime: '18:00', closeTime: '22:00', slotMinutes: 60, basePrice: 10000 });
  return { owner, ownerUser, complex, courtA: complex.courts[0], courtB: complex.courts[1] };
}

const END = { '18:00': '19:00', '19:00': '20:00', '20:00': '21:00', '21:00': '22:00' } as Record<string, string>;

/** Past days are never generated by the API: materializes the whole day of a court by hand. */
async function pastDay(courtId: string, date: string, overrides: Record<string, 'BLOCKED' | 'OCCUPIED'> = {}) {
  const turns: Record<string, { id: string }> = {};
  for (const start of Object.keys(END)) {
    turns[start] = await prisma.turn.create({
      data: { courtId, date, startTime: start, endTime: END[start], price: 10000, state: overrides[start] ?? 'AVAILABLE' },
    });
  }
  return turns;
}

async function pastBooking(
  complexId: string,
  turnId: string,
  opts: { name: string; phone: string; paid?: boolean; fixedBookingId?: string; type?: 'PLAYER' | 'CLASS'; recordedById: string }
) {
  const r = await prisma.reservation.create({
    data: {
      turnId, complexId, guestName: opts.name, guestPhone: opts.phone, type: opts.type ?? 'PLAYER',
      fixedBookingId: opts.fixedBookingId ?? null,
    },
  });
  await prisma.turn.update({ where: { id: turnId }, data: { state: 'OCCUPIED' } });
  await prisma.payment.create({
    data: { payableType: 'RESERVATION', payableId: r.id, amount: 10000, status: opts.paid ? 'PAID' : 'PENDING', date: dateFromToday(-2), recordedById: opts.recordedById },
  });
  return r;
}

describe('owner analytics', () => {
  beforeAll(async () => {
    await resetDb();
  });

  it('computes occupancy, revenue by type, top clients and cancellations', async () => {
    const { owner, ownerUser, complex, courtA, courtB } = await setup();
    const day = dateFromToday(-2);
    const a = await pastDay(courtA.id, day, { '21:00': 'BLOCKED' }); // 3 bookable turns
    const b = await pastDay(courtB.id, day); // 4 bookable turns
    const fixed = await prisma.fixedBooking.create({
      data: { complexId: complex.id, courtId: courtB.id, dayOfWeek: 1, startTime: '20:00', guestName: 'Fijo', guestPhone: '2915555555', startDate: day },
    });

    await pastBooking(complex.id, a['18:00'].id, { name: 'Ana', phone: '291 456-7890', paid: true, recordedById: ownerUser.id });
    await pastBooking(complex.id, a['19:00'].id, { name: 'Ana P.', phone: '+54 9 2914567890', recordedById: ownerUser.id });
    await pastBooking(complex.id, b['20:00'].id, { name: 'Fijo', phone: '2915555555', paid: true, fixedBookingId: fixed.id, recordedById: ownerUser.id });
    await pastBooking(complex.id, b['21:00'].id, { name: 'Clase', phone: '-', type: 'CLASS', recordedById: ownerUser.id });

    await prisma.reservationCancellation.createMany({
      data: [
        { complexId: complex.id, courtId: courtA.id, date: day, startTime: '20:00', price: 10000, type: 'PLAYER', guestName: 'X', guestPhone: '1', cancelledBy: 'PLAYER', minutesBefore: 120 },
        { complexId: complex.id, courtId: courtA.id, date: day, startTime: '20:00', price: 10000, type: 'PLAYER', guestName: 'Y', guestPhone: '2', cancelledBy: 'OWNER', minutesBefore: 3000 },
      ],
    });

    const res = await owner.get(`/api/complexes/${complex.id}/analytics`).query({ from: day, to: day });
    expect(res.status).toBe(200);
    const { kpis, byType, topClients, cancellations, byCourt, heatmap } = res.body;

    expect(kpis).toMatchObject({ capacity: 7, occupiedTurns: 4, occupancyPct: 57.1, billed: 40000, collected: 20000, pending: 20000, reservations: 4, avgTicket: 10000 });
    expect(byType).toEqual({ oneOff: { count: 2, revenue: 20000 }, fixed: { count: 1, revenue: 10000 }, classes: { count: 1, revenue: 10000 } });

    // Both "Ana" bookings group by phone; the class isn't a client.
    expect(topClients[0]).toMatchObject({ reservations: 2, spent: 10000, owed: 10000 });
    expect(topClients.some((c: any) => c.name === 'Clase')).toBe(false);

    expect(cancellations).toEqual({ total: 2, byLead: { under24h: 1, from24to48h: 0, over48h: 1 }, byWho: { PLAYER: 1, OWNER: 1, PROFESSOR: 0 } });
    expect(byCourt.find((c: any) => c.courtId === courtA.id)).toMatchObject({ capacity: 3, occupied: 2 });

    const dayRow = heatmap.days.find((d: any) => d.cells.some((c: any) => c.capacity > 0));
    expect(dayRow.cells.find((c: any) => c.hour === '18')).toMatchObject({ capacity: 2, occupied: 1, pct: 50 });
  });

  it('uses the court range as capacity for past days that were never generated', async () => {
    const { owner, complex } = await setup();
    const day = dateFromToday(-10);
    const res = await owner.get(`/api/complexes/${complex.id}/analytics`).query({ from: day, to: day });
    expect(res.body.kpis).toMatchObject({ capacity: 8, occupiedTurns: 0, occupancyPct: 0 });
  });

  it('is only available to the complex owner', async () => {
    const { complex } = await setup();
    const { agent: otherOwner } = await registerUser('DUEÑO');
    const res = await otherOwner.get(`/api/complexes/${complex.id}/analytics`).query({ from: dateFromToday(-7), to: dateFromToday(0) });
    expect(res.status).toBe(403);
  });
});
