import { describe, it, expect, beforeAll, afterEach, vi } from 'vitest';
import request from 'supertest';
import {
  app,
  prisma,
  resetDb,
  registerUser,
  createComplexForOwner,
  configureCourts,
  dateFromToday,
} from './helpers';
import { parseDateString } from '../src/services/schedule.service';

// Edge cases that cross features (bookings × fixed bookings × class schedules
// × court ranges × time of day). Numbered after the review list they came from.

const GUEST = { guestName: 'Invitado', guestPhone: '2911234567' };

/** Freezes `new Date()` (server included, it runs in-process) at today + dayOffset, HH:MM local time. */
function setNow(time: string, dayOffset = 0) {
  vi.useFakeTimers({ toFake: ['Date'] });
  const d = new Date(vi.getRealSystemTime());
  const [h, m] = time.split(':').map(Number);
  d.setDate(d.getDate() + dayOffset);
  d.setHours(h, m, 0, 0);
  vi.setSystemTime(d);
}

type Range = Partial<{ openTime: string; closeTime: string; slotMinutes: number; basePrice: number }>;

async function ownerWithComplex(range: Range = {}) {
  const { agent: owner, user: ownerUser } = await registerUser('DUEÑO');
  const complex = await createComplexForOwner(owner);
  await configureCourts(owner, complex, range);
  return { owner, ownerUser, complex, court: complex.courts[0], courtB: complex.courts[1] };
}

/** Complex with 60' turns 08:00–23:00 and a professor approved in it. */
async function withProfessor(range: Range = { openTime: '08:00', closeTime: '23:00', slotMinutes: 60, basePrice: 10000 }) {
  const base = await ownerWithComplex(range);
  const { agent: professor, user: professorUser } = await registerUser('PROFESOR', { name: 'Profe Test' });
  const joinReq = await professor.post('/api/professors/requests').send({ complexId: base.complex.id });
  await base.owner
    .put(`/api/professors/complexes/${base.complex.id}/professor-requests/${joinReq.body.request.id}`)
    .send({ status: 'APPROVED' });
  return { ...base, professor, professorUser };
}

async function getTurn(complexId: string, date: string, courtId: string, startTime: string): Promise<any> {
  // The public endpoint generates the turns but only says whether they're taken;
  // who booked them is read straight from the database.
  const res = await request(app).get(`/api/complexes/${complexId}/turns`).query({ from: date, to: date });
  const found = res.body.turns?.find((t: any) => t.courtId === courtId && t.startTime === startTime);
  return found ? prisma.turn.findUnique({ where: { id: found.id }, include: { reservation: true } }) : undefined;
}

async function createSchedule(professor: any, complexId: string, courtId: string, date: string, startTime: string, endTime: string) {
  const res = await professor.post('/api/professors/class-schedules').send({
    complexId, courtId, daysOfWeek: [parseDateString(date).dayOfWeek], startTime, endTime,
  });
  expect(res.status).toBe(201);
  return res.body.schedule;
}

async function enroll(professor: any, schedule: any, date: string, startTime: string, name: string, price = 5000) {
  const res = await professor.post('/api/professors/enrollments').send({
    classScheduleId: schedule.id, dayOfWeek: parseDateString(date).dayOfWeek, startTime, price,
    newStudent: { name, phone: '2911111111' },
  });
  return res;
}

async function account(professor: any, studentId: string) {
  return (await professor.get(`/api/professors/students/${studentId}/account`)).body;
}

/** A class of the schedule that already took place (past days are never generated by the API). */
async function givePastClass(scheduleId: string, complexId: string, courtId: string, date: string, startTime: string, endTime: string, professorId: string) {
  const turn = await prisma.turn.create({ data: { courtId, date, startTime, endTime, price: 10000, state: 'OCCUPIED' } });
  return prisma.reservation.create({
    data: {
      turnId: turn.id, complexId, professorId, userId: professorId, classScheduleId: scheduleId,
      guestName: 'Clase', guestPhone: '-', type: 'CLASS',
    },
  });
}

describe('edge cases', () => {
  beforeAll(async () => {
    await resetDb();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  // ── 1. Booking turns that already started ──────────────────────────────

  it('1. rejects booking a turn that already started today or a past date, but allows a later one today', async () => {
    setNow('15:00');
    const { complex, court } = await ownerWithComplex({ openTime: '08:00', closeTime: '23:00', slotMinutes: 90 });
    const today = dateFromToday(0);

    const started = await getTurn(complex.id, today, court.id, '14:00');
    const res = await request(app).post(`/api/turns/${started.id}/reservations`).send(GUEST);
    expect([400, 409]).toContain(res.status);
    expect((await prisma.turn.findUnique({ where: { id: started.id } }))?.state).toBe('AVAILABLE');

    const past = await prisma.turn.create({
      data: { courtId: court.id, date: dateFromToday(-1), startTime: '20:00', endTime: '21:30', price: 12000 },
    });
    const pastRes = await request(app).post(`/api/turns/${past.id}/reservations`).send(GUEST);
    expect([400, 409]).toContain(pastRes.status);

    const later = await getTurn(complex.id, today, court.id, '15:30');
    expect((await request(app).post(`/api/turns/${later.id}/reservations`).send(GUEST)).status).toBe(201);
  });

  // ── 2. Classes that started before the schedule / enrollment existed ───

  it('2a. a class schedule created at night does not book the classes of today that already started', async () => {
    setNow('21:00');
    const { professor, complex, court } = await withProfessor();
    const today = dateFromToday(0);
    await createSchedule(professor, complex.id, court.id, today, '18:00', '19:00');

    const turn = await getTurn(complex.id, today, court.id, '18:00');
    expect(turn.reservation).toBeNull();
  });

  it('2b. a student enrolled at night is not charged the class that took place earlier that day', async () => {
    setNow('10:00');
    const { professor, complex, court } = await withProfessor();
    const today = dateFromToday(0);
    const schedule = await createSchedule(professor, complex.id, court.id, today, '18:00', '19:00');

    setNow('21:00');
    const res = await enroll(professor, schedule, today, '18:00', 'Llegó Tarde');
    expect(res.status).toBe(201);
    expect((await account(professor, res.body.enrollment.studentId)).balance.owed).toBe(0);
  });

  // ── 3. Removing a student / schedule after today's class ────────────────

  it('3. removing a student or the whole schedule at night keeps the class they took that day charged', async () => {
    setNow('10:00');
    const { professor, complex, court } = await withProfessor();
    const today = dateFromToday(0);
    const schedule = await createSchedule(professor, complex.id, court.id, today, '18:00', '19:00');
    const ana = (await enroll(professor, schedule, today, '18:00', 'Ana')).body.enrollment;
    const beto = (await enroll(professor, schedule, today, '18:00', 'Beto')).body.enrollment;

    setNow('21:00');
    expect((await account(professor, ana.studentId)).balance.owed).toBe(5000);

    expect((await professor.delete(`/api/professors/enrollments/${ana.id}`)).status).toBe(200);
    expect((await account(professor, ana.studentId)).balance.owed).toBe(5000);

    expect((await professor.delete(`/api/professors/class-schedules/${schedule.id}`)).status).toBe(200);
    expect((await account(professor, beto.studentId)).balance.owed).toBe(5000);
  });

  // ── 4. Deleting a student ───────────────────────────────────────────────

  it('4. deleting a student takes them out of their classes and frees the spot', async () => {
    const { professor, complex, court } = await withProfessor();
    const date = dateFromToday(3);
    const schedule = await createSchedule(professor, complex.id, court.id, date, '09:00', '10:00');
    const enrollments = [];
    for (const name of ['Ana', 'Beto', 'Caro', 'Dani']) {
      enrollments.push((await enroll(professor, schedule, date, '09:00', name)).body.enrollment);
    }

    expect((await professor.delete(`/api/professors/students/${enrollments[0].studentId}`)).status).toBe(200);

    const grid = await professor.get('/api/professors/weekly-classes');
    const nine = grid.body.classes.find((c: any) => c.startTime === '09:00');
    expect(nine.students.map((s: any) => s.name)).toEqual(['Beto', 'Caro', 'Dani']);

    expect((await enroll(professor, schedule, date, '09:00', 'Eze')).status).toBe(201);
  });

  // ── 5. Fixed booking over a professor's class schedule ──────────────────

  it('5. rejects a fixed booking on a slot that belongs to a class schedule', async () => {
    const { owner, professor, complex, court } = await withProfessor();
    const date = dateFromToday(3);
    const schedule = await createSchedule(professor, complex.id, court.id, date, '18:00', '20:00');

    const fixed = await owner.post(`/api/complexes/${complex.id}/fixed-bookings`).send({
      courtId: court.id, dayOfWeek: parseDateString(date).dayOfWeek, startTime: '18:00', guestName: 'Pisador', guestPhone: '2917778888',
    });
    expect(fixed.status).toBe(409);

    // Weeks not generated yet still go to the professor.
    const farTurn = await getTurn(complex.id, dateFromToday(24), court.id, '18:00');
    expect(farTurn.reservation?.classScheduleId).toBe(schedule.id);
  });

  // ── 6. Changing the court's turn length under a class schedule ──────────

  it('6. changing the turn length of a court never leaves an enrolled student out of the weekly grid', async () => {
    const { owner, professor, complex, court } = await withProfessor();
    const date = dateFromToday(3);
    const schedule = await createSchedule(professor, complex.id, court.id, date, '18:00', '20:00');
    expect((await enroll(professor, schedule, date, '19:00', 'Colgado')).status).toBe(201);

    await owner.put(`/api/complexes/${complex.id}/courts`).send({
      courts: complex.courts.map((c: any, i: number) => ({
        id: c.id, name: c.name, order: i, openTime: '08:00', closeTime: '23:00', slotMinutes: 90, basePrice: 10000,
      })),
      resolveConflicts: 'CANCEL',
    });

    const grid = await professor.get('/api/professors/weekly-classes');
    const shown = grid.body.classes.flatMap((c: any) => c.students.map((s: any) => s.enrollmentId));
    const active = await prisma.classEnrollment.findMany({ where: { classScheduleId: schedule.id, endDate: null } });
    for (const e of active) expect(shown).toContain(e.id);
  });

  // ── 7. Deleting a court with history ────────────────────────────────────

  it('7. deleting a court keeps the past revenue and the students’ debt of that court', async () => {
    const { owner, ownerUser, professor, professorUser, complex, court, courtB } = await withProfessor();
    const yesterday = dateFromToday(-1);

    // A player's past reservation on court B, already paid.
    const pastTurn = await prisma.turn.create({
      data: { courtId: courtB.id, date: yesterday, startTime: '10:00', endTime: '11:00', price: 10000, state: 'OCCUPIED' },
    });
    const pastRes = await prisma.reservation.create({
      data: { turnId: pastTurn.id, complexId: complex.id, guestName: 'Pagó', guestPhone: '2911234567' },
    });
    await prisma.payment.create({
      data: { payableType: 'RESERVATION', payableId: pastRes.id, amount: 10000, status: 'PAID', date: yesterday, recordedById: ownerUser.id },
    });

    // A class that took place on court B, with a student that owes it.
    const schedule = await createSchedule(professor, complex.id, courtB.id, yesterday, '15:00', '16:00');
    const e = (await enroll(professor, schedule, yesterday, '15:00', 'Deudor', 7000)).body.enrollment;
    await prisma.classEnrollment.update({ where: { id: e.id }, data: { startDate: dateFromToday(-14) } });
    await givePastClass(schedule.id, complex.id, courtB.id, yesterday, '15:00', '16:00', professorUser.id);
    expect((await account(professor, e.studentId)).balance.owed).toBe(7000);

    const onlyCourtA = {
      courts: [{ id: court.id, name: court.name, order: 0, openTime: '08:00', closeTime: '23:00', slotMinutes: 60, basePrice: 10000 }],
      resolveConflicts: 'CANCEL',
    };

    // While the professor's schedule is active the court can't go, not even forcing it.
    const blocked = await owner.put(`/api/complexes/${complex.id}/courts`).send(onlyCourtA);
    expect(blocked.status).toBe(409);
    expect(blocked.body.conflictType).toBe('CLASS_SCHEDULES');
    expect(blocked.body.classSchedules[0]).toMatchObject({ classScheduleId: schedule.id, professorName: 'Profe Test' });

    expect((await professor.delete(`/api/professors/class-schedules/${schedule.id}`)).status).toBe(200);
    const del = await owner.put(`/api/complexes/${complex.id}/courts`).send(onlyCourtA);
    expect(del.status).toBe(200);
    expect((await owner.get(`/api/complexes/${complex.id}/schedule`)).body.courts).toHaveLength(1);

    const stats = await owner.get(`/api/complexes/${complex.id}/reservations`).query({ from: yesterday, to: yesterday });
    expect(stats.body.stats.totalCollected).toBe(10000);
    expect((await account(professor, e.studentId)).balance.owed).toBe(7000);
  });

  // ── 8. Cancelling what already happened ─────────────────────────────────

  it('8a. the owner cancelling a class that already took place does not erase the students’ debt', async () => {
    const { owner, professor, professorUser, complex, court } = await withProfessor();
    const pastDate = dateFromToday(-6);
    const schedule = await createSchedule(professor, complex.id, court.id, pastDate, '15:00', '16:00');
    const e = (await enroll(professor, schedule, pastDate, '15:00', 'Deudor', 7000)).body.enrollment;
    await prisma.classEnrollment.update({ where: { id: e.id }, data: { startDate: dateFromToday(-14) } });
    const reservation = await givePastClass(schedule.id, complex.id, court.id, pastDate, '15:00', '16:00', professorUser.id);
    expect((await account(professor, e.studentId)).balance.owed).toBe(7000);

    await owner.delete(`/api/reservations/${reservation.id}`);
    expect((await account(professor, e.studentId)).balance.owed).toBe(7000);
  });

  it('8b. a player cannot cancel a reservation that already took place', async () => {
    const { complex, court } = await ownerWithComplex();
    const { agent: player, user: playerUser } = await registerUser('JUGADOR');
    const turn = await prisma.turn.create({
      data: { courtId: court.id, date: dateFromToday(-1), startTime: '20:00', endTime: '21:30', price: 12000, state: 'OCCUPIED' },
    });
    const reservation = await prisma.reservation.create({
      data: { turnId: turn.id, complexId: complex.id, userId: playerUser.id, ...GUEST },
    });

    const res = await player.delete(`/api/reservations/${reservation.id}`);
    expect(res.status).not.toBe(200);
    expect(await prisma.reservation.findUnique({ where: { id: reservation.id } })).not.toBeNull();
  });

  // ── 9. Block then unblock under a fixed booking ─────────────────────────

  it('9. a turn the owner blocked and then freed again goes back to its fixed booking', async () => {
    const { owner, complex, court } = await ownerWithComplex();
    const date = dateFromToday(3);
    const turn = await getTurn(complex.id, date, court.id, '20:00');
    await owner.patch(`/api/complexes/${complex.id}/turns/${turn.id}`).send({ state: 'BLOCKED' });

    const fixed = await owner.post(`/api/complexes/${complex.id}/fixed-bookings`).send({
      courtId: court.id, dayOfWeek: parseDateString(date).dayOfWeek, startTime: '20:00', guestName: 'Los Fijos', guestPhone: '2917778888',
    });
    expect(fixed.body.skippedDates).toContain(date);

    await owner.patch(`/api/complexes/${complex.id}/turns/${turn.id}`).send({ state: 'AVAILABLE' });
    const after = await getTurn(complex.id, date, court.id, '20:00');
    expect(after.reservation?.fixedBookingId).toBe(fixed.body.fixedBooking.id);
  });

  // ── 10. KEEP over a fixed booking that falls out of range ───────────────

  it('10. shrinking the range with KEEP does not leave an active fixed booking that can never book again', async () => {
    const { owner, complex, court } = await ownerWithComplex();
    const date = dateFromToday(3);
    await owner.post(`/api/complexes/${complex.id}/fixed-bookings`).send({
      courtId: court.id, dayOfWeek: parseDateString(date).dayOfWeek, startTime: '21:30', guestName: 'Noche', guestPhone: '2917778888',
    });

    const res = await owner.put(`/api/complexes/${complex.id}/courts`).send({
      courts: complex.courts.map((c: any, i: number) => ({
        id: c.id, name: c.name, order: i, openTime: '08:00', closeTime: '18:00', slotMinutes: 90, basePrice: 12000,
      })),
      resolveConflicts: 'KEEP',
    });
    expect(res.status).toBe(200);

    const list = await owner.get(`/api/complexes/${complex.id}/fixed-bookings`);
    expect(list.body.fixedBookings.filter((fb: any) => fb.startTime === '21:30')).toHaveLength(0);
  });

  // ── 11. Fixed booking that ends before it starts ────────────────────────

  it('11. rejects a fixed booking whose end date is already in the past', async () => {
    const { owner, complex, court } = await ownerWithComplex();
    const res = await owner.post(`/api/complexes/${complex.id}/fixed-bookings`).send({
      courtId: court.id, dayOfWeek: 1, startTime: '20:00', guestName: 'Vencido', guestPhone: '2917778888', endDate: dateFromToday(-1),
    });
    expect(res.status).toBe(400);
  });

  // ── 12. "Mis reservas" matched by email ─────────────────────────────────

  it('12a. someone who booked as a guest and then registered with that email can see and cancel it', async () => {
    const { complex, court } = await ownerWithComplex();
    const email = `guest-${Date.now()}@test.local`;
    const turn = await getTurn(complex.id, dateFromToday(2), court.id, '18:30');
    const booking = await request(app).post(`/api/turns/${turn.id}/reservations`).send({ ...GUEST, guestEmail: email });
    expect(booking.status).toBe(201);

    const { agent: player } = await registerUser('JUGADOR', { email });
    const mine = await player.get('/api/reservations/my');
    expect(mine.body.reservations.map((r: any) => r.id)).toContain(booking.body.reservation.id);
    expect((await player.delete(`/api/reservations/${booking.body.reservation.id}`)).status).toBe(200);
  });

  it('12b. a reservation another logged-in user made with my email does not show up in my reservations', async () => {
    const { complex, court } = await ownerWithComplex();
    const { agent: victim, user: victimUser } = await registerUser('JUGADOR');
    const { agent: other } = await registerUser('JUGADOR');
    const turn = await getTurn(complex.id, dateFromToday(2), court.id, '17:00');
    const booking = await other.post(`/api/turns/${turn.id}/reservations`).send({ ...GUEST, guestEmail: victimUser.email });
    expect(booking.status).toBe(201);

    const mine = await victim.get('/api/reservations/my');
    expect(mine.body.reservations.map((r: any) => r.id)).not.toContain(booking.body.reservation.id);
  });

  // ── 13. Changing what a student pays ────────────────────────────────────

  it('13. a new enrollment price applies from the next class on; the classes already given keep theirs', async () => {
    const { professor, professorUser, complex, court } = await withProfessor();
    const pastDate = dateFromToday(-6);
    const schedule = await createSchedule(professor, complex.id, court.id, pastDate, '15:00', '16:00');
    const e = (await enroll(professor, schedule, pastDate, '15:00', 'Aumento', 7000)).body.enrollment;
    await prisma.classEnrollment.update({ where: { id: e.id }, data: { startDate: dateFromToday(-14) } });
    await prisma.classEnrollmentPrice.updateMany({ where: { enrollmentId: e.id }, data: { fromDate: dateFromToday(-14) } });
    await givePastClass(schedule.id, complex.id, court.id, pastDate, '15:00', '16:00', professorUser.id);

    expect((await professor.put(`/api/professors/enrollments/${e.id}`).send({ price: 9000 })).status).toBe(200);
    expect((await account(professor, e.studentId)).balance.owed).toBe(7000);

    // The next class (tomorrow, same weekday) is charged at the new price once it takes place.
    const nextDate = dateFromToday(1);
    expect((await getTurn(complex.id, nextDate, court.id, '15:00')).reservation?.classScheduleId).toBe(schedule.id);
    setNow('16:00', 1);
    const after = await account(professor, e.studentId);
    expect(after.balance).toMatchObject({ owed: 16000, classesCharged: 2 });
    expect(after.charges.map((c: any) => c.price)).toEqual([9000, 7000]);
  });

  // ── 14. Concurrent enrollments ──────────────────────────────────────────

  it('14. concurrent enrollments never put more than 4 students in a class', async () => {
    const { professor, complex, court } = await withProfessor();
    const date = dateFromToday(4);
    const schedule = await createSchedule(professor, complex.id, court.id, date, '11:00', '12:00');

    const results = await Promise.all(
      ['A1', 'A2', 'A3', 'A4', 'A5', 'A6'].map((name) => enroll(professor, schedule, date, '11:00', name))
    );
    expect(results.filter((r) => r.status === 201).length).toBeLessThanOrEqual(4);
    const active = await prisma.classEnrollment.count({ where: { classScheduleId: schedule.id, endDate: null } });
    expect(active).toBeLessThanOrEqual(4);
  });

  // ── 15. Courts that close at midnight ───────────────────────────────────

  it('15. a court closing at 24:00 works for bookings, fixed bookings and class schedules', async () => {
    const { owner, professor, complex, court, courtB } = await withProfessor({ openTime: '21:00', closeTime: '24:00', slotMinutes: 90, basePrice: 10000 });
    const date = dateFromToday(2);

    const turns = (await request(app).get(`/api/complexes/${complex.id}/turns`).query({ from: date, to: date })).body.turns
      .filter((t: any) => t.courtId === court.id);
    expect(turns.map((t: any) => t.startTime)).toEqual(['21:00', '22:30']);
    expect(['00:00', '24:00']).toContain(turns[1].endTime);

    expect((await request(app).post(`/api/turns/${turns[1].id}/reservations`).send(GUEST)).status).toBe(201);

    const fixed = await owner.post(`/api/complexes/${complex.id}/fixed-bookings`).send({
      courtId: court.id, dayOfWeek: parseDateString(dateFromToday(3)).dayOfWeek, startTime: '22:30', guestName: 'Trasnoche', guestPhone: '2917778888',
    });
    expect(fixed.status).toBe(201);

    const schedule = await createSchedule(professor, complex.id, courtB.id, dateFromToday(4), '21:00', '24:00');
    expect(schedule.endTime).toBe('24:00');
    const grid = await professor.get('/api/professors/weekly-classes');
    expect(grid.body.classes.map((c: any) => c.startTime)).toEqual(['21:00', '22:30']);
  });

  // ── 16. Server running in UTC ───────────────────────────────────────────

  it('16. "today" follows Argentina time even when the server runs in UTC', async () => {
    const artDate = dateFromToday(2);
    const previousTZ = process.env.TZ;
    process.env.TZ = 'UTC';
    try {
      // 22:30 in Argentina = 01:30 UTC of the next day.
      vi.useFakeTimers({ toFake: ['Date'] });
      vi.setSystemTime(new Date(`${artDate}T22:30:00-03:00`));

      const { professor, professorUser, complex, court, courtB } = await withProfessor({ openTime: '08:00', closeTime: '24:00', slotMinutes: 60, basePrice: 10000 });

      const defaultDay = await request(app).get(`/api/complexes/${complex.id}/turns`);
      expect(defaultDay.body.turns[0]?.date).toBe(artDate);

      // The 23:00 turn of today (Argentina) hasn't started: bookable.
      const lateTurn = await getTurn(complex.id, artDate, courtB.id, '23:00');
      expect(lateTurn).toBeDefined();
      expect((await request(app).post(`/api/turns/${lateTurn.id}/reservations`).send(GUEST)).status).toBe(201);

      // ...and a class at 23:00 today isn't charged yet.
      const schedule = await createSchedule(professor, complex.id, court.id, artDate, '23:00', '24:00');
      const e = (await enroll(professor, schedule, artDate, '23:00', 'Nocturno', 6000)).body.enrollment;
      await prisma.classEnrollment.update({ where: { id: e.id }, data: { startDate: dateFromToday(-14) } });
      const existing = await prisma.turn.findFirst({ where: { courtId: court.id, date: artDate, startTime: '23:00' }, include: { reservation: true } });
      if (!existing?.reservation) {
        if (existing) await prisma.turn.delete({ where: { id: existing.id } });
        await givePastClass(schedule.id, complex.id, court.id, artDate, '23:00', '00:00', professorUser.id);
      }
      expect((await account(professor, e.studentId)).balance.owed).toBe(0);
    } finally {
      vi.useRealTimers();
      if (previousTZ === undefined) delete process.env.TZ;
      else process.env.TZ = previousTZ;
    }
  });
});
