import { describe, it, expect, beforeAll } from 'vitest';
import { prisma, resetDb, registerUser, createComplexForOwner, configureCourts, dateFromToday } from './helpers';
import { parseDateString } from '../src/services/schedule.service';

/** Complex with 60' turns 08:00–23:00 at $10.000 and a professor approved in it. */
async function setup() {
  const { agent: owner } = await registerUser('DUEÑO');
  const complex = await createComplexForOwner(owner);
  await configureCourts(owner, complex, { openTime: '08:00', closeTime: '23:00', slotMinutes: 60, basePrice: 10000 });
  const { agent: professor, user: professorUser } = await registerUser('PROFESOR', { name: 'Profe Test' });
  const joinReq = await professor.post('/api/professors/requests').send({ complexId: complex.id });
  await owner.put(`/api/professors/complexes/${complex.id}/professor-requests/${joinReq.body.request.id}`).send({ status: 'APPROVED' });
  return { professor, professorUser, complex, court: complex.courts[0] };
}

/** A class of the schedule that already took place (past days are never generated by the API). */
async function givePastClass(scheduleId: string, complexId: string, courtId: string, date: string, startTime: string, professorId: string) {
  const end = `${String(Number(startTime.slice(0, 2)) + 1).padStart(2, '0')}:00`;
  const turn = await prisma.turn.create({ data: { courtId, date, startTime, endTime: end, price: 10000, state: 'OCCUPIED' } });
  await prisma.reservation.create({
    data: { turnId: turn.id, complexId, professorId, userId: professorId, classScheduleId: scheduleId, guestName: 'Clase', guestPhone: '-', type: 'CLASS' },
  });
}

describe('professor analytics', () => {
  beforeAll(async () => {
    await resetDb();
  });

  it('reports billed, collected, court cost, attendance, occupancy and students', async () => {
    const { professor, professorUser, complex, court } = await setup();
    const week1 = dateFromToday(-14);
    const week2 = dateFromToday(-7);
    const dow = parseDateString(week1).dayOfWeek;

    const sched = await professor.post('/api/professors/class-schedules').send({
      complexId: complex.id, courtId: court.id, daysOfWeek: [dow], startTime: '18:00', endTime: '20:00',
    });
    expect(sched.status).toBe(201);
    const scheduleId = sched.body.schedule.id;

    const enroll = async (name: string, price: number) => {
      const res = await professor.post('/api/professors/enrollments').send({
        classScheduleId: scheduleId, dayOfWeek: dow, startTime: '18:00', price, newStudent: { name, phone: '2911111111' },
      });
      expect(res.status).toBe(201);
      return prisma.classEnrollment.findFirstOrThrow({ where: { classScheduleId: scheduleId, student: { name } } });
    };
    const ana = await enroll('Ana', 5000);
    const beto = await enroll('Beto', 6000);
    // Backdate both enrollments so the past classes count.
    await prisma.classEnrollment.updateMany({ where: { id: { in: [ana.id, beto.id] } }, data: { startDate: week1 } });
    await prisma.classEnrollmentPrice.updateMany({ where: { enrollmentId: { in: [ana.id, beto.id] } }, data: { fromDate: week1 } });

    await givePastClass(scheduleId, complex.id, court.id, week1, '18:00', professorUser.id);
    await givePastClass(scheduleId, complex.id, court.id, week2, '18:00', professorUser.id);
    // Beto missed week 2: not charged.
    await prisma.classAbsence.create({ data: { enrollmentId: beto.id, date: week2 } });

    const pay = await professor.post(`/api/professors/students/${ana.studentId}/payments`).send({ amount: 5000, date: week2 });
    expect(pay.status).toBe(201);

    const res = await professor.get('/api/professors/analytics').query({ from: week1, to: dateFromToday(0) });
    expect(res.status).toBe(200);
    const { kpis, attendance, classesWithRoom, byComplex, debtors } = res.body;

    // Ana 2 × 5000 + Beto 1 × 6000; two turns of $10.000 used.
    expect(kpis).toMatchObject({
      billed: 16000,
      collected: 5000,
      courtCost: 20000,
      margin: -4000,
      classesGiven: 2,
      attendancePct: 75,
      debtTotal: 11000,
      studentsOwing: 2,
      activeStudents: 2,
    });
    // 18:00 has 2 of 4 seats taken, 19:00 is empty: 2 of 8 seats.
    expect(kpis.occupancyPct).toBe(25);
    expect(classesWithRoom).toHaveLength(2);

    expect(attendance[0]).toMatchObject({ name: 'Beto', attended: 1, missed: 1, pct: 50 });
    expect(byComplex[0]).toMatchObject({ classesGiven: 2, billed: 16000, courtCost: 20000 });
    expect(debtors.map((d: any) => [d.name, d.owes])).toEqual([['Beto', 6000], ['Ana', 5000]]);
  });

  it('counts students who left in the range', async () => {
    const { professor, complex, court } = await setup();
    const dow = parseDateString(dateFromToday(3)).dayOfWeek;
    const sched = await professor.post('/api/professors/class-schedules').send({
      complexId: complex.id, courtId: court.id, daysOfWeek: [dow], startTime: '10:00', endTime: '11:00',
    });
    await professor.post('/api/professors/enrollments').send({
      classScheduleId: sched.body.schedule.id, dayOfWeek: dow, startTime: '10:00', price: 5000, newStudent: { name: 'Caro', phone: '2911111111' },
    });
    const e = await prisma.classEnrollment.findFirstOrThrow({ where: { classScheduleId: sched.body.schedule.id } });
    expect((await professor.delete(`/api/professors/enrollments/${e.id}`)).status).toBe(200);

    const res = await professor.get('/api/professors/analytics').query({ from: dateFromToday(-30), to: dateFromToday(7) });
    expect(res.body.kpis).toMatchObject({ newStudents: 1, leftStudents: 1, activeStudents: 0 });
  });
});
