import { describe, it, expect, beforeAll } from 'vitest';
import request from 'supertest';
import {
  app,
  prisma,
  resetDb,
  registerUser,
  createComplexForOwner,
  configureCourts,
  dateFromToday,
} from './helpers';
import { parseDateString } from '../src/services/schedule.service';

/** Owner complex with 60' turns 08:00–23:00 and a professor approved in it. */
async function setup() {
  const { agent: owner } = await registerUser('DUEÑO');
  const complex = await createComplexForOwner(owner);
  await configureCourts(owner, complex, { openTime: '08:00', closeTime: '23:00', slotMinutes: 60, basePrice: 10000 });

  const { agent: professor, user: professorUser } = await registerUser('PROFESOR', { name: 'Profe Test' });
  const joinReq = await professor.post('/api/professors/requests').send({ complexId: complex.id });
  await owner
    .put(`/api/professors/complexes/${complex.id}/professor-requests/${joinReq.body.request.id}`)
    .send({ status: 'APPROVED' });

  return { owner, professor, professorUser, complex, court: complex.courts[0] };
}

async function getTurn(complexId: string, date: string, courtId: string, startTime: string): Promise<any> {
  // The public endpoint generates the turns but only says whether they're taken;
  // who booked them is read straight from the database.
  const res = await request(app).get(`/api/complexes/${complexId}/turns`).query({ from: date, to: date });
  const found = res.body.turns?.find((t: any) => t.courtId === courtId && t.startTime === startTime);
  return found ? prisma.turn.findUnique({ where: { id: found.id }, include: { reservation: true } }) : undefined;
}

/** A class of the schedule that already took place (past days are never generated by the API). */
async function givePastClass(scheduleId: string, complexId: string, courtId: string, date: string, startTime: string, professorId: string) {
  const turn = await prisma.turn.create({
    data: { courtId, date, startTime, endTime: `${String(Number(startTime.slice(0, 2)) + 1).padStart(2, '0')}:00`, price: 10000, state: 'OCCUPIED' },
  });
  await prisma.reservation.create({
    data: {
      turnId: turn.id,
      complexId,
      professorId,
      userId: professorId,
      classScheduleId: scheduleId,
      guestName: 'Clase',
      guestPhone: '-',
      type: 'CLASS',
    },
  });
}

describe('professor class schedules', () => {
  beforeAll(async () => {
    await resetDb();
  });

  it('books every turn of the window on the chosen weekdays as CLASS, without showing up as a fixed booking', async () => {
    const { owner, professor, complex, court } = await setup();
    const dayA = dateFromToday(2);
    const dayB = dateFromToday(3);

    const create = await professor.post('/api/professors/class-schedules').send({
      complexId: complex.id,
      courtId: court.id,
      daysOfWeek: [parseDateString(dayA).dayOfWeek, parseDateString(dayB).dayOfWeek],
      startTime: '18:00',
      endTime: '20:00',
    });
    expect(create.status).toBe(201);
    expect(create.body.skipped).toEqual([]);
    const scheduleId = create.body.schedule.id;

    for (const date of [dayA, dayB]) {
      for (const start of ['18:00', '19:00']) {
        const turn = await getTurn(complex.id, date, court.id, start);
        expect(turn.state).toBe('OCCUPIED');
        expect(turn.reservation).toMatchObject({ type: 'CLASS', classScheduleId: scheduleId });
      }
    }
    expect((await getTurn(complex.id, dayA, court.id, '20:00')).state).toBe('AVAILABLE');

    const fixed = await owner.get(`/api/complexes/${complex.id}/fixed-bookings`);
    expect(fixed.body.fixedBookings).toHaveLength(0);

    const list = await professor.get('/api/professors/class-schedules');
    expect(list.body.schedules).toHaveLength(1);
    expect(list.body.schedules[0]).toMatchObject({ startTime: '18:00', endTime: '20:00', court: { id: court.id } });
  });

  it('rejects unlinked professors, windows without a full turn, and overlapping schedules', async () => {
    const { professor, complex, court } = await setup();
    const day = parseDateString(dateFromToday(4)).dayOfWeek;
    const body = { complexId: complex.id, courtId: court.id, daysOfWeek: [day], startTime: '10:00', endTime: '12:00' };

    const { agent: stranger } = await registerUser('PROFESOR');
    expect((await stranger.post('/api/professors/class-schedules').send(body)).status).toBe(403);

    expect((await professor.post('/api/professors/class-schedules').send({ ...body, endTime: '10:30' })).status).toBe(400);

    expect((await professor.post('/api/professors/class-schedules').send(body)).status).toBe(201);
    const overlap = await professor.post('/api/professors/class-schedules').send({ ...body, startTime: '11:00', endTime: '13:00' });
    expect(overlap.status).toBe(409);
  });

  it('builds the weekly grid and enrolls up to 4 students per class', async () => {
    const { professor, complex, court } = await setup();
    const day = parseDateString(dateFromToday(5)).dayOfWeek;
    const create = await professor.post('/api/professors/class-schedules').send({
      complexId: complex.id, courtId: court.id, daysOfWeek: [day], startTime: '09:00', endTime: '11:00',
    });
    const scheduleId = create.body.schedule.id;

    const grid = await professor.get('/api/professors/weekly-classes');
    expect(grid.status).toBe(200);
    expect(grid.body.classes.map((c: any) => c.startTime)).toEqual(['09:00', '10:00']);

    const slot = { classScheduleId: scheduleId, dayOfWeek: day, startTime: '09:00' };
    const first = await professor.post('/api/professors/enrollments').send({ ...slot, price: 6000, newStudent: { name: 'Ana', phone: '2911111111' } });
    expect(first.status).toBe(201);
    const anaId = first.body.enrollment.studentId;

    expect((await professor.post('/api/professors/enrollments').send({ ...slot, price: 6000, studentId: anaId })).status).toBe(409);

    for (const name of ['Beto', 'Caro', 'Dani']) {
      const r = await professor.post('/api/professors/enrollments').send({ ...slot, price: 6000, newStudent: { name, phone: '2912222222' } });
      expect(r.status).toBe(201);
    }
    const fifth = await professor.post('/api/professors/enrollments').send({ ...slot, price: 6000, newStudent: { name: 'Eze', phone: '2913333333' } });
    expect(fifth.status).toBe(409);

    // Same student can be in another class of the week.
    const other = await professor.post('/api/professors/enrollments').send({ ...slot, startTime: '10:00', price: 15000, studentId: anaId });
    expect(other.status).toBe(201);

    const after = await professor.get('/api/professors/weekly-classes');
    const nine = after.body.classes.find((c: any) => c.startTime === '09:00');
    expect(nine.students.map((s: any) => s.name)).toEqual(['Ana', 'Beto', 'Caro', 'Dani']);
    expect(after.body.classes.find((c: any) => c.startTime === '10:00').students[0].price).toBe(15000);
  });

  it('charges each class that took place and subtracts the recorded payments', async () => {
    const { professor, professorUser, complex, court } = await setup();
    // Six days ago: same weekday as tomorrow, so no class of this schedule has started today.
    const pastDate = dateFromToday(-6);
    const day = parseDateString(pastDate).dayOfWeek;
    const create = await professor.post('/api/professors/class-schedules').send({
      complexId: complex.id, courtId: court.id, daysOfWeek: [day], startTime: '15:00', endTime: '16:00',
    });
    const scheduleId = create.body.schedule.id;

    const enroll = await professor.post('/api/professors/enrollments').send({
      classScheduleId: scheduleId, dayOfWeek: day, startTime: '15:00', price: 7000, newStudent: { name: 'Deudor', phone: '2914444444' },
    });
    const { id: enrollmentId, studentId } = enroll.body.enrollment;

    // The student was already in the class last week, and that class happened.
    await prisma.classEnrollment.update({ where: { id: enrollmentId }, data: { startDate: dateFromToday(-14) } });
    await givePastClass(scheduleId, complex.id, court.id, pastDate, '15:00', professorUser.id);

    const account = await professor.get(`/api/professors/students/${studentId}/account`);
    expect(account.status).toBe(200);
    expect(account.body.balance).toEqual({ paid: 0, owed: 7000, balance: -7000, classesCharged: 1 });
    expect(account.body.charges[0]).toMatchObject({ date: pastDate, startTime: '15:00', price: 7000 });

    // Marked absent: that class isn't charged; undoing it charges it again.
    const absent = await professor.post(`/api/professors/enrollments/${enrollmentId}/absences`).send({ date: pastDate });
    expect(absent.status).toBe(201);
    const whileAbsent = await professor.get(`/api/professors/students/${studentId}/account`);
    expect(whileAbsent.body.balance).toMatchObject({ owed: 0, classesCharged: 0 });
    expect(whileAbsent.body.absences[0]).toMatchObject({ date: pastDate, startTime: '15:00', price: 7000 });

    expect((await professor.post(`/api/professors/enrollments/${enrollmentId}/absences`).send({ date: dateFromToday(-5) })).status).toBe(400);

    expect((await professor.delete(`/api/professors/enrollments/${enrollmentId}/absences/${pastDate}`)).status).toBe(200);
    const backToCharged = await professor.get(`/api/professors/students/${studentId}/account`);
    expect(backToCharged.body.balance.owed).toBe(7000);

    // Ahead of time (the student let the professor know): listed, charges nothing.
    const nextDate = dateFromToday(1);
    expect((await professor.post(`/api/professors/enrollments/${enrollmentId}/absences`).send({ date: nextDate })).status).toBe(201);
    const withUpcoming = await professor.get(`/api/professors/students/${studentId}/account`);
    expect(withUpcoming.body.absences.map((a: any) => a.date)).toContain(nextDate);
    expect(withUpcoming.body.balance.owed).toBe(7000);
    await professor.delete(`/api/professors/enrollments/${enrollmentId}/absences/${nextDate}`);

    const pay = await professor.post(`/api/professors/students/${studentId}/payments`).send({ amount: 5000 });
    expect(pay.status).toBe(201);
    const afterPay = await professor.get(`/api/professors/students/${studentId}/account`);
    expect(afterPay.body.balance.balance).toBe(-2000);

    // Removing the student from the class keeps the debt already generated.
    await professor.delete(`/api/professors/enrollments/${enrollmentId}`);
    const afterRemove = await professor.get(`/api/professors/students/${studentId}/account`);
    expect(afterRemove.body.balance.owed).toBe(7000);

    // A payment recorded by mistake can be deleted.
    await professor.delete(`/api/professors/payments/${pay.body.payment.id}`);
    const afterDelete = await professor.get(`/api/professors/students/${studentId}/account`);
    expect(afterDelete.body.balance.balance).toBe(-7000);

    const { agent: otherProf } = await registerUser('PROFESOR');
    expect((await otherProf.get(`/api/professors/students/${studentId}/account`)).status).toBe(404);
  });

  it('keeps a class the owner cancelled free, and deleting the schedule frees the upcoming classes', async () => {
    const { owner, professor, complex, court } = await setup();
    const date = dateFromToday(3);
    const create = await professor.post('/api/professors/class-schedules').send({
      complexId: complex.id, courtId: court.id, daysOfWeek: [parseDateString(date).dayOfWeek], startTime: '12:00', endTime: '13:00',
    });
    const scheduleId = create.body.schedule.id;

    const booked = await getTurn(complex.id, date, court.id, '12:00');
    expect((await owner.delete(`/api/reservations/${booked.reservation.id}`)).status).toBe(200);
    const cancelled = await getTurn(complex.id, date, court.id, '12:00');
    expect(cancelled.state).toBe('AVAILABLE');
    expect(cancelled.reservation).toBeNull();

    const nextWeek = dateFromToday(10);
    expect((await getTurn(complex.id, nextWeek, court.id, '12:00')).reservation?.classScheduleId).toBe(scheduleId);

    expect((await professor.delete(`/api/professors/class-schedules/${scheduleId}`)).status).toBe(200);
    expect((await getTurn(complex.id, nextWeek, court.id, '12:00')).state).toBe('AVAILABLE');
    expect((await professor.get('/api/professors/class-schedules')).body.schedules).toHaveLength(0);
  });
});
